# Generated by Django 4.2.5 on 2023-09-15 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_personalinformation_delete_personalinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='personal_info',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='personal_info',
        ),
    ]
