# Generated by Django 4.2.5 on 2023-09-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
                ('linkdin', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('school_1', models.CharField(max_length=100)),
                ('degree_1', models.CharField(max_length=100)),
                ('year_1', models.CharField(max_length=100)),
                ('school_2', models.CharField(max_length=100)),
                ('degree_2', models.CharField(max_length=100)),
                ('year_2', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('skill_1', models.CharField(max_length=100)),
                ('skill_2', models.CharField(max_length=100)),
                ('skill_3', models.CharField(max_length=100)),
                ('skill_4', models.CharField(max_length=100)),
                ('skill_5', models.CharField(max_length=100)),
                ('skill_6', models.CharField(max_length=100)),
                ('skill_7', models.CharField(max_length=100)),
                ('skill_8', models.CharField(max_length=100)),
                ('skill_9', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('language_1', models.CharField(max_length=100)),
                ('language_2', models.CharField(max_length=100)),
                ('interest', models.CharField(max_length=100)),
                ('interest_1', models.CharField(max_length=100)),
                ('interest_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='resume',
            name='educations',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
