# Generated by Django 4.1.3 on 2022-12-15 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
