# Generated by Django 4.2.6 on 2023-10-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_myuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='myuser',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
