# Generated by Django 4.2.6 on 2023-10-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_subject_student_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
