# Generated by Django 4.2.5 on 2023-09-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField(max_length=10)),
                ('pin_code', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
