# Generated by Django 4.1.3 on 2022-12-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=1000)),
                ('catagory', models.CharField(choices=[('m', 'men'), ('w', 'women'), ('k', 'kids'), ('mk', 'men kit'), ('wt', 'watch'), ('f', 'featured_product'), ('l', 'latest_product'), ('b', 'brands'), ('t', 'testimonial'), ('o', 'offers'), ('ban', 'banner')], max_length=50)),
                ('images', models.ImageField(upload_to='media/productimages')),
            ],
        ),
    ]
