# Generated by Django 4.1.3 on 2022-12-15 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productapp', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Email_id', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=500)),
                ('land_mark', models.CharField(max_length=100)),
                ('State', models.CharField(choices=[('Rajasthan', 'Rajasthan'), ('Haryana', 'Haryana'), ('Delhi', 'Delhi'), ('UP', 'UP'), ('HP', 'HP'), ('Punjab', 'Punjab'), ('Bihar', 'Bihar'), ('MP', 'Mp'), ('Gujarat', 'Gujrat'), ('Chandigarh', 'Chandigarh'), ('Goa', 'Goa')], max_length=100)),
                ('City', models.CharField(choices=[('Jaipur', 'Jaipur'), ('Udaipur', 'Udaipur'), ('Ajmer', 'Ajmer'), ('Badmer', 'Badmer'), ('Dosa', 'Dosa')], max_length=100)),
                ('pin_code', models.IntegerField()),
                ('Mobile_no', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
