# Generated by Django 4.1.3 on 2022-12-15 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
