# Generated by Django 4.2.1 on 2023-06-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pic',
            name='name',
            field=models.CharField(default='mohit', max_length=50),
        ),
    ]
