# Generated by Django 4.2.1 on 2023-07-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('proejct_link', models.CharField(max_length=100)),
                ('updated_date', models.DateTimeField()),
            ],
        ),
    ]
